use crate::lcs::hugo::{ensure_hextra_theme, ensure_site_dirs, write_json, write_text};
use anyhow::{Context, Result, anyhow};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::fs;
use std::path::{Path, PathBuf};

#[cfg(feature = "smart")]
use crate::tools::smart::{AstParser, LeanDeclKind, LeanGraphAnalyzer};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct IpfsHaStep {
    pub route: String,
    pub component: String,
    pub file: String,
    pub line_anchor: String,
    pub ha_delta: String,
    pub proof_refs: Vec<String>,
    pub excerpt: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct IpfsHaSnapshot {
    pub source_root: String,
    pub proof_theorems: Vec<String>,
    pub theorem_cards: Vec<IpfsHaTheorem>,
    pub steps: Vec<IpfsHaStep>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct IpfsHaTheorem {
    pub name: String,
    pub short_name: String,
    pub line_anchor: String,
    pub signature: String,
    pub doc_comment: Option<String>,
    pub local_deps: Vec<String>,
    pub unresolved_refs: Vec<String>,
    pub excerpt: String,
}

pub const DEFAULT_IPFS_HA_SNAPSHOT_PATH: &str =
    "/mnt/riffcastle/castle/garage/ipfs-ha-docs/data/ipfs_ha_add_path.json";

const IPFS_HA_HUGO_CONFIG: &str = r#"baseURL: "https://docs.riff.cc/ipfs-ha/"
languageCode: "en-gb"
title: "IPFS HA Docs"
theme: "hextra"
enableGitInfo: false

params:
  description: "IPFS HA add-path documentation generated by LCS."
  navbar:
    displayTitle: true
    displayLogo: false
    width: wide
  page:
    width: full
  footer:
    displayPoweredBy: false

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: Home
      pageRef: /
      weight: 1
    - name: Docs
      pageRef: /docs
      weight: 2
    - name: Reference
      pageRef: /docs/reference
      weight: 3
"#;

const DOCS_INDEX: &str = "---\ntitle: Docs\ncascade:\n  type: docs\n---\n\nStitched views across nginx, Cluster, Kubo, flatfs-mw, and the Lean proof surface.\n";
const ARCH_INDEX: &str =
    "---\ntitle: Architecture\n---\n\nAdd-path and patch-surface explanations for the shared-repo HA stack.\n";
const REF_INDEX: &str =
    "---\ntitle: Reference\n---\n\nStructured snapshots emitted by the IPFS HA LCS dogfood generator.\n";

fn frontmatter(title: &str, weight: usize) -> String {
    format!(
        "---\ntitle: {title}\nweight: {weight}\n---\n\n",
        title = title,
        weight = weight
    )
}

fn read_text(path: &Path) -> Result<String> {
    fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))
}

fn relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .display()
        .to_string()
}

fn find_line(content: &str, needle: &str) -> Result<usize> {
    content
        .lines()
        .position(|line| line.contains(needle))
        .map(|idx| idx + 1)
        .ok_or_else(|| anyhow!("failed to find pattern `{needle}`"))
}

fn excerpt(content: &str, line: usize, radius: usize) -> String {
    let lines: Vec<&str> = content.lines().collect();
    if lines.is_empty() {
        return String::new();
    }

    let start = line.saturating_sub(radius + 1);
    let end = usize::min(lines.len(), line + radius);
    lines[start..end].join("\n")
}

fn proof_theorems(source_root: &Path) -> Result<Vec<String>> {
    let proof_path = source_root.join("proofs/FlatfsMw.lean");
    let source = read_text(&proof_path)?;

    #[cfg(feature = "smart")]
    {
        let mut parser = AstParser::new();
        let graph =
            LeanGraphAnalyzer::analyze(&proof_path.display().to_string(), &source, &mut parser)
                .ok_or_else(|| {
                    anyhow!("failed to build Lean graph for {}", proof_path.display())
                })?;

        return Ok(graph
            .declarations
            .into_iter()
            .filter(|decl| matches!(decl.kind, LeanDeclKind::Theorem))
            .map(|decl| decl.short_name)
            .collect());
    }

    #[cfg(not(feature = "smart"))]
    {
        let mut theorems = Vec::new();
        for line in source.lines() {
            let trimmed = line.trim();
            if let Some(rest) = trimmed.strip_prefix("theorem ") {
                if let Some(name) = rest.split_whitespace().next() {
                    theorems.push(name.trim_end_matches(':').to_string());
                }
            }
        }
        return Ok(theorems);
    }
}

fn proof_surface(source_root: &Path) -> Result<Vec<IpfsHaTheorem>> {
    let proof_path = source_root.join("proofs/FlatfsMw.lean");
    let source = read_text(&proof_path)?;

    #[cfg(feature = "smart")]
    {
        let mut parser = AstParser::new();
        let graph =
            LeanGraphAnalyzer::analyze(&proof_path.display().to_string(), &source, &mut parser)
                .ok_or_else(|| {
                    anyhow!("failed to build Lean graph for {}", proof_path.display())
                })?;

        return Ok(graph
            .declarations
            .into_iter()
            .filter(|decl| matches!(decl.kind, LeanDeclKind::Theorem))
            .map(|decl| IpfsHaTheorem {
                name: decl.name,
                short_name: decl.short_name,
                line_anchor: format!("L{}", decl.start_line),
                signature: decl.signature,
                doc_comment: decl.doc_comment,
                local_deps: decl.local_deps,
                unresolved_refs: decl.unresolved_refs,
                excerpt: excerpt(&source, decl.start_line, 6),
            })
            .collect());
    }

    #[cfg(not(feature = "smart"))]
    {
        let mut cards = Vec::new();
        for (idx, line) in source.lines().enumerate() {
            let trimmed = line.trim();
            if let Some(rest) = trimmed.strip_prefix("theorem ") {
                if let Some(name) = rest.split_whitespace().next() {
                    cards.push(IpfsHaTheorem {
                        name: name.trim_end_matches(':').to_string(),
                        short_name: name.trim_end_matches(':').to_string(),
                        line_anchor: format!("L{}", idx + 1),
                        signature: trimmed.to_string(),
                        doc_comment: None,
                        local_deps: Vec::new(),
                        unresolved_refs: Vec::new(),
                        excerpt: excerpt(&source, idx + 1, 6),
                    });
                }
            }
        }
        return Ok(cards);
    }
}

fn slugify(name: &str) -> String {
    let mut slug = String::new();
    let mut last_was_dash = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            slug.push(ch.to_ascii_lowercase());
            last_was_dash = false;
        } else if !last_was_dash {
            slug.push('-');
            last_was_dash = true;
        }
    }
    slug.trim_matches('-').to_string()
}

pub fn default_ipfs_ha_snapshot_path() -> PathBuf {
    PathBuf::from(DEFAULT_IPFS_HA_SNAPSHOT_PATH)
}

pub fn load_ipfs_ha_snapshot(path: &Path) -> Result<IpfsHaSnapshot> {
    let content = read_text(path)?;
    serde_json::from_str(&content)
        .with_context(|| format!("failed to parse IPFS HA snapshot {}", path.display()))
}

pub fn discover_ipfs_ha_snapshot(project_root: &Path) -> Option<PathBuf> {
    let explicit = default_ipfs_ha_snapshot_path();
    if explicit.exists() {
        let looks_like_ipfs_repo = project_root.join("proofs/FlatfsMw.lean").exists()
            || project_root.join("go-ds-flatfs-mw").exists()
            || project_root.join("kubo-v0.40.1").exists()
            || project_root
                .file_name()
                .and_then(|s| s.to_str())
                .map(|s| s.contains("IPFS-HA") || s.contains("ipfs"))
                .unwrap_or(false);
        if looks_like_ipfs_repo {
            return Some(explicit);
        }
    }

    let sibling = project_root.join("data/ipfs_ha_add_path.json");
    if sibling.exists() {
        return Some(sibling);
    }

    None
}

pub fn query_ipfs_ha_snapshot(snapshot: &IpfsHaSnapshot, query: &str) -> Vec<String> {
    let query_lc = query.to_ascii_lowercase();
    let mut blocks = Vec::new();

    for step in &snapshot.steps {
        let haystack = format!(
            "{} {} {} {} {} {}",
            step.route,
            step.component,
            step.file,
            step.line_anchor,
            step.ha_delta,
            step.excerpt
        )
        .to_ascii_lowercase();

        if haystack.contains(&query_lc)
            || query_lc.contains("ipfs")
            || query_lc.contains("kubo")
            || query_lc.contains("cluster")
            || query_lc.contains("flatfs")
            || query_lc.contains("moosefs")
            || query_lc.contains("proof")
        {
            blocks.push(format!(
                "IPFS-HA step: `{component}` at `{file}:{line}`\nRoute: `{route}`\nDelta: {delta}\n\n```\n{excerpt}\n```",
                component = step.component,
                file = step.file,
                line = step.line_anchor,
                route = step.route,
                delta = step.ha_delta,
                excerpt = step.excerpt
            ));
        }
    }

    for theorem in &snapshot.theorem_cards {
        let haystack = format!(
            "{} {} {} {} {} {}",
            theorem.name,
            theorem.short_name,
            theorem.signature,
            theorem.excerpt,
            theorem.local_deps.join(" "),
            theorem.unresolved_refs.join(" ")
        )
        .to_ascii_lowercase();

        if haystack.contains(&query_lc)
            || query_lc.contains("lean")
            || query_lc.contains("proof")
            || query_lc.contains("theorem")
        {
            blocks.push(format!(
                "IPFS-HA theorem: `{name}` at `proofs/FlatfsMw.lean:{line}`\nSignature: `{sig}`\nLocal deps: `{deps}`\nUnresolved refs: `{unresolved}`\n\n```\n{excerpt}\n```",
                name = theorem.short_name,
                line = theorem.line_anchor,
                sig = theorem.signature,
                deps = if theorem.local_deps.is_empty() {
                    "(none)".to_string()
                } else {
                    theorem.local_deps.join(", ")
                },
                unresolved = if theorem.unresolved_refs.is_empty() {
                    "(none)".to_string()
                } else {
                    theorem.unresolved_refs.join(", ")
                },
                excerpt = theorem.excerpt
            ));
        }
    }

    blocks.truncate(8);
    blocks
}

fn build_step(
    source_root: &Path,
    route: &str,
    component: &str,
    relative_path: &str,
    needle: &str,
    ha_delta: &str,
    proof_refs: &[String],
) -> Result<IpfsHaStep> {
    let path = source_root.join(relative_path);
    let content = read_text(&path)?;
    let line = find_line(&content, needle)?;

    Ok(IpfsHaStep {
        route: route.to_string(),
        component: component.to_string(),
        file: relative(source_root, &path),
        line_anchor: format!("L{}", line),
        ha_delta: ha_delta.to_string(),
        proof_refs: proof_refs.to_vec(),
        excerpt: excerpt(&content, line, 6),
    })
}

fn add_path_page(snapshot: &IpfsHaSnapshot) -> String {
    let mut out = frontmatter("IPFS HA Add Path", 1);
    out.push_str(
        "This page stitches the current add path across the deployed facade, Cluster, Kubo, shared-repo deltas, flatfs-mw, and the Lean proof surface.\n\n",
    );

    out.push_str("## Route Split\n\n");
    out.push_str("- `https://.../api/v0/add` -> Cluster facade\n");
    out.push_str("- `https://.../kubo/api/v0/add` -> direct Kubo add path\n");
    out.push_str("- Both routes force `chunker=size-1048576`\n\n");

    let mut grouped = std::collections::BTreeMap::<String, Vec<&IpfsHaStep>>::new();
    for step in &snapshot.steps {
        grouped.entry(step.route.clone()).or_default().push(step);
    }

    for (route, steps) in grouped {
        out.push_str(&format!("## `{}`\n\n", route));
        for step in steps {
            out.push_str(&format!(
                "### {}\n\nFile: `{}` `{}`\n\n{}\n\n",
                step.component, step.file, step.line_anchor, step.ha_delta
            ));

            if !step.proof_refs.is_empty() {
                out.push_str("Proof refs: ");
                out.push_str(
                    &step
                        .proof_refs
                        .iter()
                        .map(|name| format!("`{}`", name))
                        .collect::<Vec<_>>()
                        .join(", "),
                );
                out.push_str("\n\n");
            }

            let lang = if step.file.ends_with(".go") {
                "go"
            } else if step.file.ends_with(".lean") {
                "lean"
            } else {
                "text"
            };
            out.push_str(&format!("```{lang}\n{}\n```\n\n", step.excerpt));
        }
    }

    out
}

fn proof_surface_page(snapshot: &IpfsHaSnapshot) -> String {
    let mut out = frontmatter("Proof Surface", 1);
    out.push_str(
        "The current Lean proof anchor for the multiwriter fork lives in `proofs/FlatfsMw.lean`.\n\n",
    );
    out.push_str("## What Exists Now\n\n");
    out.push_str(
        "- theorem extraction through the SmartRead Lean graph layer\n- local declaration dependency edges\n- unresolved reference surfacing for imported proof machinery\n- generated theorem cards and theorem pages\n\n",
    );
    out.push_str("## Theorems\n\n");
    for theorem in &snapshot.theorem_cards {
        out.push_str(&format!(
            "- [`{}`](/docs/reference/theorems/{})\n",
            theorem.short_name,
            slugify(&theorem.short_name)
        ));
    }
    out.push_str("\nThese are surface-structure theorem views. They are already useful for proof-to-code linkage and fast orientation, but they are not yet elaborated proof truth, tactic-state traces, or kernel dependency closure.\n");
    out
}

fn theorem_index_page(snapshot: &IpfsHaSnapshot) -> String {
    let mut out = frontmatter("Theorems", 2);
    out.push_str(
        "Generated theorem cards for the current `FlatfsMw.lean` proof surface.\n\n",
    );
    for theorem in &snapshot.theorem_cards {
        out.push_str(&format!(
            "## [{}](/docs/reference/theorems/{})\n\n",
            theorem.short_name,
            slugify(&theorem.short_name)
        ));
        if let Some(doc) = &theorem.doc_comment {
            out.push_str(&format!("{}\n\n", doc));
        }
        out.push_str(&format!("Signature: `{}`\n\n", theorem.signature));
        let deps = if theorem.local_deps.is_empty() {
            "none".to_string()
        } else {
            theorem.local_deps
                .iter()
                .map(|dep| format!("`{dep}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!("Local deps: {}\n\n", deps));
    }
    out
}

fn theorem_page(theorem: &IpfsHaTheorem) -> String {
    let mut out = frontmatter(&theorem.short_name, 1);
    out.push_str(&format!(
        "Source: `proofs/FlatfsMw.lean` `{}`\n\n",
        theorem.line_anchor
    ));
    if let Some(doc) = &theorem.doc_comment {
        out.push_str(&format!("{}\n\n", doc));
    }
    out.push_str(&format!("## Signature\n\n`{}`\n\n", theorem.signature));
    out.push_str("## Local Dependencies\n\n");
    if theorem.local_deps.is_empty() {
        out.push_str("- none\n");
    } else {
        for dep in &theorem.local_deps {
            out.push_str(&format!("- `{}`\n", dep));
        }
    }
    out.push_str("\n## External / Unresolved References\n\n");
    if theorem.unresolved_refs.is_empty() {
        out.push_str("- none\n");
    } else {
        for dep in &theorem.unresolved_refs {
            out.push_str(&format!("- `{}`\n", dep));
        }
    }
    out.push_str("\n## Excerpt\n\n```lean\n");
    out.push_str(&theorem.excerpt);
    out.push_str("\n```\n");
    out
}

fn home_page(snapshot: &IpfsHaSnapshot) -> String {
    format!(
        r#"---
title: IPFS HA
---

# IPFS HA

This is the first LCS dogfood surface aimed directly at the Kubo HA work.

It exists to make the add path legible across:

- nginx ingress split
- IPFS Cluster facade
- Kubo add pipeline
- shared-repo patch surface
- `go-ds-flatfs-mw`
- the Lean proof anchor

Current stitched steps: **{steps}**

{{{{< cards >}}}}
  {{{{< card link="/docs/architecture/add-path" title="Add Path" subtitle="The exact cross-repo add flow and its HA deltas." >}}}}
  {{{{< card link="/docs/reference/proof-surface" title="Proof Surface" subtitle="The Lean theorem anchor behind the flatfs-mw patch." >}}}}
  {{{{< card link="/docs/reference/theorems" title="Theorem Cards" subtitle="Generated theorem pages for the current proof surface." >}}}}
{{{{< /cards >}}}}
"#,
        steps = snapshot.steps.len()
    )
}

pub fn generate_ipfs_ha_site(source: &Path, output: &Path) -> Result<()> {
    ensure_site_dirs(output)?;
    ensure_hextra_theme(output)?;

    let proof_refs = proof_theorems(source)?;
    let theorem_cards = proof_surface(source)?;

    let steps = vec![
        build_step(
            source,
            "/api/v0/add",
            "Ingress: Cluster facade",
            "deploy/testbed-ipfs.koneksi.co.kr",
            "location = /api/v0/add {",
            "Public add requests terminate in nginx, stay on real TLS, and are forced onto the Cluster proxy with `chunker=size-1048576`.",
            &[],
        )?,
        build_step(
            source,
            "/api/v0/add",
            "Cluster route registration",
            "ipfs-cluster/api/ipfsproxy/ipfsproxy.go",
            "Path(\"/add\").",
            "The Cluster IPFS proxy explicitly hijacks `/add`, so the public add path is Cluster-mediated rather than forwarded straight to Kubo.",
            &[],
        )?,
        build_step(
            source,
            "/api/v0/add",
            "Cluster add handler",
            "ipfs-cluster/api/ipfsproxy/ipfsproxy.go",
            "func (proxy *Server) addHandler(",
            "Cluster translates IPFS-style add semantics into Cluster add params, preserving the facade while still driving the shared backend.",
            &[],
        )?,
        build_step(
            source,
            "/kubo/api/v0/add",
            "Ingress: direct Kubo path",
            "deploy/testbed-ipfs.koneksi.co.kr",
            "location = /kubo/api/v0/add {",
            "The direct Kubo path bypasses Cluster but still forces the 1 MiB chunker and keeps the same TLS ingress surface.",
            &[],
        )?,
        build_step(
            source,
            "/kubo/api/v0/add",
            "Kubo Unixfs API entry",
            "kubo-v0.40.1/core/coreapi/unixfs.go",
            "func (api *UnixfsAPI) Add(",
            "Shared-repo mode in the CoreAPI add entry skips add-path blockservice existence checks so later blocks do not stall behind per-block `Has()` churn.",
            &[],
        )?,
        build_step(
            source,
            "shared backend",
            "Adder commit and pin barrier",
            "kubo-v0.40.1/core/coreunix/add.go",
            "func (adder *Adder) AddAllAndPin(",
            "This is still the durable completion barrier: DAG flush, root selection, close, and pin semantics define when add is actually done.",
            &[],
        )?,
        build_step(
            source,
            "shared backend",
            "Shared-repo blockstore/provide delta",
            "kubo-v0.40.1/core/node/storage.go",
            "func shouldDeferImmediateBlockProvides(",
            "Shared-repo mode defers immediate per-block provides so ingest is not forced through synchronous provider churn on every block Put.",
            &[],
        )?,
        build_step(
            source,
            "shared backend",
            "Shared-repo lock skip",
            "kubo-v0.40.1/repo/fsrepo/fsrepo.go",
            "if os.Getenv(\"IPFS_SHARED_REPO\") == \"true\" {",
            "HA mode skips the repo lock entirely because multiple Kubo nodes are expected to share the same DFS-backed repo safely.",
            &[],
        )?,
        build_step(
            source,
            "shared backend",
            "flatfs-mw async publish path",
            "go-ds-flatfs-mw/flatfs.go",
            "func (bt *flatfsBatch) Put(",
            "The fork changes the temp/publication path to be key-local and asynchronous, making shared-filesystem multiwriter safe with much less cross-key serialization.",
            &proof_refs,
        )?,
        build_step(
            source,
            "proof",
            "Lean proof anchor",
            "proofs/FlatfsMw.lean",
            "theorem upstream_final_unchanged",
            "The proof file captures the minimal-change claim: final paths are unchanged, temp paths are injective, and same-key/same-path semantics stay collision-free.",
            &proof_refs,
        )?,
    ];

    let snapshot = IpfsHaSnapshot {
        source_root: source.display().to_string(),
        proof_theorems: proof_refs,
        theorem_cards,
        steps,
    };

    write_text(output, "hugo.yaml", IPFS_HA_HUGO_CONFIG)?;
    write_text(
        output,
        "layouts/_partials/scripts/search.html",
        "{{/* Search disabled for offline local builds. */}}\n",
    )?;
    write_text(output, "content/_index.md", &home_page(&snapshot))?;
    write_text(output, "content/docs/_index.md", DOCS_INDEX)?;
    write_text(output, "content/docs/architecture/_index.md", ARCH_INDEX)?;
    write_text(output, "content/docs/reference/_index.md", REF_INDEX)?;
    write_text(
        output,
        "content/docs/reference/theorems.md",
        &theorem_index_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/architecture/add-path.md",
        &add_path_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/reference/proof-surface.md",
        &proof_surface_page(&snapshot),
    )?;
    for theorem in &snapshot.theorem_cards {
        write_text(
            output,
            &format!(
                "content/docs/reference/theorems/{}.md",
                slugify(&theorem.short_name)
            ),
            &theorem_page(theorem),
        )?;
    }
    write_json(output, "data/ipfs_ha_add_path.json", &json!(snapshot))?;

    Ok(())
}
