use crate::lcs::hugo::{ensure_hextra_theme, ensure_site_dirs, write_json, write_text};
use anyhow::{Context, Result};
use serde::Serialize;
use serde_json::json;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Serialize)]
struct JetpackSnapshot {
    package: BTreeMap<String, String>,
    top_level_modules: Vec<String>,
    module_families: Vec<String>,
    connection_backends: Vec<String>,
    provisioners: Vec<String>,
    docs_files: Vec<String>,
    example_files: Vec<String>,
    readme_sections: BTreeMap<String, String>,
}

const JETPACK_HUGO_CONFIG: &str = r#"baseURL: "https://docs.riff.cc/jetpack/"
languageCode: "en-gb"
title: "Jetpack Docs"
theme: "hextra"
enableGitInfo: false

params:
  description: "Jetpack documentation generated by LCS."
  navbar:
    displayTitle: true
    displayLogo: false
    width: wide
  page:
    width: full
  footer:
    displayPoweredBy: false

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: Home
      pageRef: /
      weight: 1
    - name: Docs
      pageRef: /docs
      weight: 2
"#;

const INTRO_INDEX: &str = "---\ntitle: Introduction\n---\n\nEntry-point pages for understanding the Jetpack repository quickly.\n";
const ARCH_INDEX: &str = "---\ntitle: Architecture\n---\n\nSubsystem and implementation slices derived from the Jetpack source tree.\n";
const USAGE_INDEX: &str = "---\ntitle: Usage\n---\n\nExamples, debt, and operator-facing guidance extracted from the repository.\n";
const REF_INDEX: &str =
    "---\ntitle: Reference\n---\n\nStructured repository data exported by LCS.\n";

fn escape_html(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn read_text(path: &Path) -> Result<String> {
    fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))
}

fn parse_package_fields(cargo_toml: &str) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    let mut in_package = false;

    for raw in cargo_toml.lines() {
        let line = raw.trim();
        if line.starts_with('[') {
            in_package = line == "[package]";
            continue;
        }
        if !in_package || line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            let cleaned = value.trim().trim_matches('"').to_string();
            map.insert(key.trim().to_string(), cleaned);
        }
    }

    map
}

fn parse_readme_sections(readme: &str) -> BTreeMap<String, String> {
    let mut sections = BTreeMap::new();
    let mut current = String::from("Overview");
    let mut buffer = Vec::new();

    for line in readme.lines() {
        if line.starts_with("## ") || line.starts_with("### ") {
            if !buffer.is_empty() {
                sections.insert(current.clone(), buffer.join("\n").trim().to_string());
                buffer.clear();
            }
            current = line.trim_start_matches('#').trim().to_string();
            continue;
        }
        buffer.push(line.to_string());
    }

    if !buffer.is_empty() {
        sections.insert(current, buffer.join("\n").trim().to_string());
    }

    sections
}

fn list_files(dir: &Path, max_depth: usize) -> Result<Vec<String>> {
    fn walk(
        root: &Path,
        current: &Path,
        depth: usize,
        max_depth: usize,
        out: &mut Vec<String>,
    ) -> Result<()> {
        if depth > max_depth {
            return Ok(());
        }
        let mut entries: Vec<PathBuf> = fs::read_dir(current)?
            .filter_map(|entry| entry.ok().map(|e| e.path()))
            .collect();
        entries.sort();

        for path in entries {
            if path.is_dir() {
                walk(root, &path, depth + 1, max_depth, out)?;
            } else if let Ok(relative) = path.strip_prefix(root) {
                out.push(relative.display().to_string());
            }
        }

        Ok(())
    }

    let mut out = Vec::new();
    walk(dir, dir, 0, max_depth, &mut out)?;
    Ok(out)
}

fn directory_names(dir: &Path) -> Result<Vec<String>> {
    let mut names = Vec::new();
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)?
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.is_dir())
        .collect();
    entries.sort();
    for entry in entries {
        if let Some(name) = entry.file_name().and_then(|v| v.to_str()) {
            names.push(name.to_string());
        }
    }
    Ok(names)
}

fn top_level_modules(lib_rs: &str) -> Vec<String> {
    let mut modules = Vec::new();
    for line in lib_rs.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("pub mod ") {
            let name = rest.trim_end_matches(';').trim();
            modules.push(name.to_string());
        }
    }
    modules
}

fn bullet_list(items: &[String]) -> String {
    items
        .iter()
        .map(|item| format!("- `{item}`"))
        .collect::<Vec<_>>()
        .join("\n")
}

fn frontmatter(title: &str, weight: usize) -> String {
    format!(
        "---\ntitle: {title}\nweight: {weight}\n---\n\n",
        title = title,
        weight = weight
    )
}

fn repo_map_page(snapshot: &JetpackSnapshot) -> String {
    format!(
        "{fm}Jetpack currently exposes these top-level Rust modules:\n\n{mods}\n\n## Filesystem Shape\n\n### `src/modules`\n\n{families}\n\n### `src/connection`\n\n{connections}\n\n### `src/provisioners`\n\n{provisioners}\n",
        fm = frontmatter("Repository Map", 1),
        mods = bullet_list(&snapshot.top_level_modules),
        families = bullet_list(&snapshot.module_families),
        connections = bullet_list(&snapshot.connection_backends),
        provisioners = bullet_list(&snapshot.provisioners),
    )
}

fn examples_page(snapshot: &JetpackSnapshot) -> String {
    format!(
        "{fm}Jetpack already carries a useful example corpus that LCS can turn into guided docs later.\n\n{examples}\n",
        fm = frontmatter("Examples", 1),
        examples = bullet_list(&snapshot.example_files),
    )
}

fn docs_and_debt_page(snapshot: &JetpackSnapshot) -> String {
    let technical_debt = snapshot
        .readme_sections
        .get("Technical Debt")
        .cloned()
        .unwrap_or_else(|| "No technical debt section found.".to_string());
    let roadmap = snapshot
        .readme_sections
        .get("Roadmap")
        .cloned()
        .unwrap_or_else(|| "No roadmap section found.".to_string());

    format!(
        "{fm}## Technical Debt\n\n{debt}\n\n## Roadmap\n\n{roadmap}\n",
        fm = frontmatter("Debt and Roadmap", 1),
        debt = technical_debt,
        roadmap = roadmap
    )
}

fn overview_page(snapshot: &JetpackSnapshot) -> String {
    let description = snapshot
        .package
        .get("description")
        .cloned()
        .unwrap_or_else(|| "automation platform".to_string());
    let version = snapshot
        .package
        .get("version")
        .cloned()
        .unwrap_or_else(|| "unknown".to_string());
    let homepage = snapshot
        .package
        .get("homepage")
        .cloned()
        .unwrap_or_else(|| "https://riff.cc/jetpack".to_string());
    let repo = snapshot
        .package
        .get("repository")
        .cloned()
        .unwrap_or_else(|| "https://github.com/riffcc/jetpack".to_string());

    format!(
        r#"---
title: Jetpack
---

# Jetpack

Jetpack is the first intentional LCS test case.

Current package metadata:

- version: `{version}`
- description: `{description}`
- homepage: <{homepage}>
- repository: <{repo}>

{{{{< cards >}}}}
  {{{{< card link="/docs/introduction/repository-map" title="Repository Map" subtitle="Top-level modules and subsystem layout." >}}}}
  {{{{< card link="/docs/architecture/module-families" title="Module Families" subtitle="Task, connection, playbook, and provisioner surfaces." >}}}}
  {{{{< card link="/docs/usage/examples" title="Examples" subtitle="Current example inventory from the repo." >}}}}
  {{{{< card link="/docs/usage/debt-and-roadmap" title="Debt and Roadmap" subtitle="Known debt and forward path from README." >}}}}
{{{{< /cards >}}}}
"#,
        version = version,
        description = description,
        homepage = homepage,
        repo = repo
    )
}

fn module_families_page(snapshot: &JetpackSnapshot) -> String {
    format!(
        "{fm}## Top-Level Module Families\n\n{modules}\n\n## Docs Files\n\n{docs}\n",
        fm = frontmatter("Module Families", 1),
        modules = bullet_list(&snapshot.module_families),
        docs = bullet_list(&snapshot.docs_files)
    )
}

fn playbook_engine_page(snapshot: &JetpackSnapshot) -> String {
    let playbook_related: Vec<String> = snapshot
        .top_level_modules
        .iter()
        .filter(|name| {
            name.as_str() == "playbooks" || name.as_str() == "tasks" || name.as_str() == "inventory"
        })
        .cloned()
        .collect();

    format!(
        "{fm}Jetpack's execution path revolves around inventory, playbooks, and task execution.\n\n## Relevant Exported Modules\n\n{modules}\n",
        fm = frontmatter("Playbook Engine", 1),
        modules = bullet_list(&playbook_related)
    )
}

fn connections_page(snapshot: &JetpackSnapshot) -> String {
    format!(
        "{fm}These connection backends are currently visible in the repository:\n\n{connections}\n",
        fm = frontmatter("Connections", 1),
        connections = bullet_list(&snapshot.connection_backends)
    )
}

fn provisioning_page(snapshot: &JetpackSnapshot) -> String {
    format!(
        "{fm}Current provisioner surface:\n\n{provisioners}\n",
        fm = frontmatter("Provisioning", 1),
        provisioners = bullet_list(&snapshot.provisioners)
    )
}

fn repository_data_page(snapshot: &JetpackSnapshot) -> String {
    let json_preview = escape_html(&serde_json::to_string_pretty(snapshot).unwrap_or_default());
    format!(
        "{fm}This page mirrors the structured repository snapshot that LCS exported into Hugo data.\n\n```json\n{preview}\n```\n",
        fm = frontmatter("Repository Data", 1),
        preview = json_preview
    )
}

fn capture(source: &Path) -> Result<JetpackSnapshot> {
    let cargo_toml = read_text(&source.join("Cargo.toml"))?;
    let readme = read_text(&source.join("README.md"))?;
    let lib_rs = read_text(&source.join("src/lib.rs"))?;

    Ok(JetpackSnapshot {
        package: parse_package_fields(&cargo_toml),
        top_level_modules: top_level_modules(&lib_rs),
        module_families: directory_names(&source.join("src/modules"))?,
        connection_backends: list_files(&source.join("src/connection"), 1)?,
        provisioners: list_files(&source.join("src/provisioners"), 1)?,
        docs_files: list_files(&source.join("docs"), 2)?,
        example_files: {
            let mut files = Vec::new();
            files.extend(list_files(&source.join("examples"), 2)?);
            files.extend(list_files(&source.join("jetpack_examples"), 2)?);
            files.extend(list_files(&source.join("crate-examples"), 2)?);
            files
        },
        readme_sections: parse_readme_sections(&readme),
    })
}

pub fn generate_jetpack_site(source: &Path, output: &Path) -> Result<()> {
    let snapshot = capture(source)?;

    ensure_site_dirs(output)?;
    ensure_hextra_theme(output)?;

    write_text(output, "hugo.yaml", JETPACK_HUGO_CONFIG)?;
    write_text(
        output,
        "layouts/_partials/scripts/search.html",
        "{{/* Search disabled for offline local builds. */}}\n",
    )?;
    write_text(output, "content/_index.md", &overview_page(&snapshot))?;
    write_text(
        output,
        "content/docs/_index.md",
        "---\ntitle: Docs\ncascade:\n  type: docs\n---\n\nJetpack documentation generated through LCS.\n",
    )?;
    write_text(output, "content/docs/introduction/_index.md", INTRO_INDEX)?;
    write_text(output, "content/docs/architecture/_index.md", ARCH_INDEX)?;
    write_text(output, "content/docs/usage/_index.md", USAGE_INDEX)?;
    write_text(output, "content/docs/reference/_index.md", REF_INDEX)?;
    write_text(
        output,
        "content/docs/introduction/repository-map.md",
        &repo_map_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/architecture/module-families.md",
        &module_families_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/architecture/playbook-engine.md",
        &playbook_engine_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/architecture/connections.md",
        &connections_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/architecture/provisioning.md",
        &provisioning_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/usage/examples.md",
        &examples_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/usage/debt-and-roadmap.md",
        &docs_and_debt_page(&snapshot),
    )?;
    write_text(
        output,
        "content/docs/reference/repository-data.md",
        &repository_data_page(&snapshot),
    )?;
    write_json(output, "data/jetpack.json", &json!(snapshot))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{parse_package_fields, parse_readme_sections, top_level_modules};

    #[test]
    fn package_fields_are_extracted() {
        let cargo = "[package]\nname = \"jetpack\"\nversion = \"0.1.2\"\n";
        let fields = parse_package_fields(cargo);
        assert_eq!(fields.get("name").unwrap(), "jetpack");
        assert_eq!(fields.get("version").unwrap(), "0.1.2");
    }

    #[test]
    fn readme_sections_split_on_headings() {
        let readme = "Intro\n## First\nAlpha\n## Second\nBeta";
        let sections = parse_readme_sections(readme);
        assert!(sections.contains_key("Overview"));
        assert_eq!(sections.get("First").unwrap(), "Alpha");
        assert_eq!(sections.get("Second").unwrap(), "Beta");
    }

    #[test]
    fn top_level_modules_follow_pub_mod_lines() {
        let lib_rs = "pub mod cli;\npub mod tools;\n";
        assert_eq!(top_level_modules(lib_rs), vec!["cli", "tools"]);
    }
}
