//! Message types for API responses.

use serde::{Deserialize, Serialize};

use super::{ContentBlock, Usage};

/// The reason the model stopped generating.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {
    /// The model reached a natural stopping point.
    EndTurn,
    /// The maximum token limit was reached.
    MaxTokens,
    /// A custom stop sequence was generated.
    StopSequence,
    /// The model invoked one or more tools.
    ToolUse,
    /// The turn was paused (for long-running turns).
    PauseTurn,
    /// Content was refused due to policy.
    Refusal,
}

/// A message response from the API.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Message {
    /// Unique object identifier.
    pub id: String,

    /// Object type (always "message").
    #[serde(rename = "type")]
    pub message_type: String,

    /// Conversational role (always "assistant" for responses).
    pub role: String,

    /// Content generated by the model.
    pub content: Vec<ContentBlock>,

    /// The model that generated this message.
    pub model: String,

    /// The reason generation stopped.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<StopReason>,

    /// Which custom stop sequence was generated (if any).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_sequence: Option<String>,

    /// Token usage information.
    pub usage: Usage,
}

impl Message {
    /// Returns the first text content from the message, if any.
    pub fn text(&self) -> Option<&str> {
        self.content.iter().find_map(|block| block.as_text())
    }

    /// Returns all text content concatenated.
    pub fn all_text(&self) -> String {
        self.content
            .iter()
            .filter_map(|block| block.as_text())
            .collect::<Vec<_>>()
            .join("")
    }

    /// Returns all tool use blocks from the message.
    pub fn tool_uses(&self) -> Vec<&super::ToolUseBlock> {
        self.content
            .iter()
            .filter_map(|block| block.as_tool_use())
            .collect()
    }

    /// Returns true if the model requested to use tools.
    pub fn has_tool_use(&self) -> bool {
        self.stop_reason == Some(StopReason::ToolUse)
            || self.content.iter().any(|b| b.as_tool_use().is_some())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::TextBlock;

    #[test]
    fn test_message_deserialization() {
        let json = r#"{
            "id": "msg_123",
            "type": "message",
            "role": "assistant",
            "content": [{"type": "text", "text": "Hello!"}],
            "model": "glm-4-plus",
            "stop_reason": "end_turn",
            "usage": {"input_tokens": 10, "output_tokens": 5}
        }"#;

        let message: Message = serde_json::from_str(json).unwrap();
        assert_eq!(message.id, "msg_123");
        assert_eq!(message.role, "assistant");
        assert_eq!(message.text(), Some("Hello!"));
        assert_eq!(message.stop_reason, Some(StopReason::EndTurn));
    }

    #[test]
    fn test_message_with_tool_use() {
        let json = r#"{
            "id": "msg_456",
            "type": "message",
            "role": "assistant",
            "content": [
                {"type": "text", "text": "I'll read that file."},
                {"type": "tool_use", "id": "toolu_789", "name": "read_file", "input": {"path": "/test.txt"}}
            ],
            "model": "glm-4-plus",
            "stop_reason": "tool_use",
            "usage": {"input_tokens": 20, "output_tokens": 15}
        }"#;

        let message: Message = serde_json::from_str(json).unwrap();
        assert!(message.has_tool_use());
        assert_eq!(message.tool_uses().len(), 1);
        assert_eq!(message.tool_uses()[0].name, "read_file");
    }

    #[test]
    fn test_stop_reason_variants() {
        let variants = [
            ("end_turn", StopReason::EndTurn),
            ("max_tokens", StopReason::MaxTokens),
            ("stop_sequence", StopReason::StopSequence),
            ("tool_use", StopReason::ToolUse),
            ("pause_turn", StopReason::PauseTurn),
            ("refusal", StopReason::Refusal),
        ];

        for (json_val, expected) in variants {
            let json = format!(r#""{json_val}""#);
            let reason: StopReason = serde_json::from_str(&json).unwrap();
            assert_eq!(reason, expected);
        }
    }

    #[test]
    fn test_all_text() {
        let message = Message {
            id: "msg_test".to_string(),
            message_type: "message".to_string(),
            role: "assistant".to_string(),
            content: vec![
                ContentBlock::Text(TextBlock::new("Hello, ")),
                ContentBlock::Text(TextBlock::new("world!")),
            ],
            model: "test".to_string(),
            stop_reason: Some(StopReason::EndTurn),
            stop_sequence: None,
            usage: Usage::default(),
        };

        assert_eq!(message.all_text(), "Hello, world!");
    }
}
